### ISSUE TITLE
Construcción de la ventana1 primera parte 

### ISSUE THREAD

**Issue by JuanAngelOtero** [JuanAngelOtero/Clase9#1]
Construir la ventana Ventana1 y hacer el formulario para ingresar la información del cliente

**Comment by JUANALEJANDROOTEROPEREZ** [comment]
Saludos voy a encargarme de esta funcionalidad.

**Comment by JuanAngelOtero** [comment]
Listo trabajo cumplido por favor revisar el nuevo  issue para hacer en ventana1.py el formulario de registro del usuario
