### ISSUE TITLE
Construir en la ventana1 el formulario para ingresar el usuario

### ISSUE THREAD

**Issue by JuanAngelOtero** [JuanAngelOtero/Clase9#4]
En este nuevo issue debes programar el botón de limpiar  para limpiar todos los campos.
También debes  hacer el formulario para pedir los datos del usuario.

**Comment by JUANALEJANDROOTEROPEREZ** [comment]
Voy a encargarme de este nuevo issue #4

**Comment by JuanAngelOtero** [comment]
listo este issue esta listo
