### ISSUE TITLE
Programar el botón para buscar  las preguntas de recuperación de contraseña 

### ISSUE THREAD

**Issue by JuanAngelOtero** [JuanAngelOtero/Clase9#6]
Validar que se ingrese el documento de usuario al cuan se le va a buscar la contraseña
Validar que el documento sea un dato numérico
Crear la clase usuario con sus 11 propiedades
Solo considerar un pasword
Buscar las preguntas para recuperar las contraseña

**Comment by JUANALEJANDROOTEROPEREZ** [comment]
Me voy  a encargar de este issue, voy a desarrollarlo. 
pendiente de alguna sugerencia

**Comment by JuanAngelOtero** [comment]
Listo, quedo pendiente a su primer push y pull request

**Comment by JuanAngelOtero** [comment]
Se cierra este issue # 6
